### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by zhangtj1996** [younglululu/DeepPINK#1]

**Comment by younglululu** [comment]
Send me an email, I will point you to the code and data

**Comment by zhangtj1996** [comment]
Thank you.

**Comment by zhangtj1996** [comment]
> Send me an email, I will point you to the code and data

Thank you

**Comment by xiaoleiHou214** [comment]
> Send me an email, I will point you to the code and data
I also can't find the code,can you point me too?Please

**Comment by xiaoleiHou214** [comment]
> No description provided.

Hi,do you have this code?If you have,can you provide it to me?

**Comment by zhangtj1996** [comment]
I'm very happy this work attracts a lot attention. They authors did't put the code online may due to other reasons. As a reader, I'm not authorized to distribute the code. Please email the authors directly, I believe they are willing to provide the code.
