### ISSUE TITLE
Hi, any thought on using the software to generate the knockoff?

### ISSUE THREAD

**Issue by jingyuanChou** [younglululu/DeepPINK#2]
Hi,

I crossed the repo and also interested in the knockoff generation, and went to your referred link, and there are ton of R code there, is it possible that you can specify how to use that code, I saw many functions for the knockoff generation and try to understand to logic.

**Comment by younglululu** [comment]
I think  genKnock.R is the one you should look at.

**Comment by jingyuanChou** [comment]
Hi I sent you en email, could you please have a check? I appreciate it
